<?php
/**
 * @file
 * Demo module
 */

/**
 * Implements hook_menu().
 */
function demo_module_menu() {
  $items = array();

  $items['some/path'] = array(
    'title' => '',
    'description' => '',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => '',
    'page arguments' => array(),
    'access arguments' => array('my custom permission'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function demo_module_permission() {
  $perms = array();

  $perms['my custom permission'] = array(
    'title' => '',
    'description' => '',
  );

  return $perms;
}
